import type { DashboardLocale } from "@/lib/dashboard-brand";

const EN_DASHBOARD_COPY = {
  nav: {
    meetings: "Meetings",
    tracker: "Tracker",
    dictionary: "Transcription Dictionary",
    joinMeeting: "Join Meeting",
    webhooks: "Webhooks",
    mcpSetup: "MCP Setup",
    profile: "Profile",
    admin: "Admin",
    users: "Users",
    bots: "Bots",
    settings: "Settings",
    unlockAdmin: "Unlock Admin",
    apiDocs: "API Docs",
    reportBug: "Report a Bug",
    accountBilling: "Account & Billing",
    menu: "Menu",
  },
  header: {
    toggleMenu: "Toggle menu",
    docsSr: "Full Documentation",
    docsTooltip: "Full API Documentation",
    profileApiKey: "Profile & API Key",
    account: "Account",
    logout: "Logout",
  },
  billing: {
    trialPrefix: "Trial",
    day: "day",
    days: "days",
    left: "left",
    planExpired: "Plan expired",
    subscribe: "Subscribe",
    activePlanSuffix: "plan",
  },
  login: {
    heroTitle: "Drop a bot to your meeting",
    meetingPlaceholder: "Paste meeting URL...",
    invalidMeetingUrl: "Please enter a valid meeting URL",
    unsupportedPlatformToast: "Only Google Meet and Microsoft Teams are supported right now",
    unsupportedPlatformHint: "Only Google Meet and Microsoft Teams are supported right now",
    createMeet: "Create a Meet",
    signIn: "Already have an account? Sign in",
    footer: "Open Source · Developer-first · API-first",
    serverConfigErrorTitle: "Server Configuration Error",
    serverConfigErrorDescription: "The server is not properly configured. Please contact the administrator.",
    connectionWarningTitle: "Connection Warning",
    connectionWarningDescription: "Some services may be unavailable.",
    signInTitle: "Sign in to continue",
    signInDescription: "Choose your provider to get started",
    continueGoogle: "Continue with Google",
    continueMicrosoft: "Continue with Microsoft",
    or: "Or",
    checkingServer: "Checking server...",
    signingIn: "Signing in...",
    sendingLink: "Sending link...",
    serverUnavailable: "Server Unavailable",
    continueEmail: "Continue with Email",
    back: "Back",
    checkEmailTitle: "Check your email",
    checkEmailDescription: "We sent a magic link to",
    clickEmailLink: "Click the link in the email to sign in.",
    linkExpires: "The link will expire in 15 minutes.",
    sending: "Sending...",
    resendMagicLink: "Resend magic link",
    differentEmail: "Use a different email",
    accountCreated: "Account created! Welcome to {brand}.",
    welcomeBack: "Welcome back!",
    magicLinkSent: "Magic link sent! Check your email.",
    magicLinkSentAgain: "Magic link sent again! Check your email.",
    failedSend: "Failed to send magic link",
    failedResend: "Failed to resend magic link",
    enterEmail: "Please enter your email",
    failedGoogle: "Failed to sign in with Google",
    failedMicrosoft: "Failed to sign in with Microsoft",
  },
  meetings: {
    subscriptionRequiredTitle: "Subscription required",
    subscriptionRequiredMessage: "Subscribe to a plan to create new bots and access the API.",
    viewPlans: "View Plans",
    title: "Meetings",
    description: "Browse and search your meeting transcriptions",
    joinMeeting: "Join Meeting",
    joinShort: "Join",
    searchPlaceholder: "Search meetings...",
    allPlatforms: "All Platforms",
    allStatus: "All Status",
    statuses: {
      active: "Active",
      completed: "Completed",
      failed: "Failed",
      joining: "Joining",
    },
    subscribeTitle: "Subscribe to continue",
    subscribeMessage:
      "Your trial has ended. Subscribe to a plan to create bots and access meeting transcriptions.",
    table: {
      platform: "Platform",
      meeting: "Meeting",
      status: "Status",
      duration: "Duration",
      participants: "Participants",
      time: "Time",
    },
    noMatches: "No meetings match your filters",
    noMeetings: "No meetings yet",
    joinFirst: "Join your first meeting",
    participantsMeetingTitle: "Meeting with {names}",
    statusDescriptions: {
      stopped: "Recording was stopped by user action or the system",
      meetingEnded: "Transcription completed because the meeting ended",
      kicked: "The bot left the meeting",
      admissionRejected: "The bot was not admitted to the meeting",
      completed: "Transcription completed successfully",
      failed: "An error occurred during processing",
      needsHumanHelp: "The bot has stalled and needs human attention",
      active: "The bot is currently in the meeting, recording and transcribing",
      joining: "The bot is attempting to join the meeting",
      awaitingAdmission: "Waiting in the lobby for admission",
      requested: "Bot startup has been requested",
      stopping: "Stopping the recording",
      unknown: "Unable to determine the current status",
    },
  },
  joinModal: {
    title: "Join a Meeting",
    description: "Paste a Google Meet, Zoom, or Teams URL to start transcribing automatically",
    modeMeeting: "Meeting",
    modeBrowser: "Browser",
    modeMeetingDescription: "The bot joins your Google Meet, Zoom, or Teams meeting URL and transcribes it.",
    modeBrowserDescription: "Opens a persistent remote browser you can control via VNC or CDP.",
    browserDescription: "Remote browser with VNC, CDP, and SSH. Configure git workspace in Profile settings.",
    starting: "Starting...",
    startBrowserSession: "Start Browser Session",
    invalidTitle: "Invalid meeting",
    invalidDescription: "Please enter a valid Google Meet, Zoom, or Teams URL or meeting code",
    platformRequiredTitle: "Platform required",
    platformRequiredDescription:
      "This URL doesn't match a known meeting platform. Please select Google Meet, Zoom, or Teams.",
    passcodeRequiredTitle: "Passcode required",
    passcodeRequiredDescription: "Microsoft Teams meetings require a passcode",
    botJoining: "Bot joining meeting",
    botJoiningDescription: "The transcription bot is connecting...",
    subscriptionRequiredTitle: "Subscription required",
    subscriptionRequiredDescription: "Subscribe to a plan to create bots.",
    zoomAuthTitle: "Zoom authentication required",
    zoomAuthDescription:
      "Redirecting to Zoom. Sign in with the Zoom account that owns or is allowed to use the app.",
    zoomAuthStartFailed: "Failed to start Zoom authentication",
    platformNeeded:
      "URL recognized as a meeting link, but vendor isn't auto-detected. Pick the platform — the bot will navigate the URL directly.",
    platformRadioLabel: "Select meeting platform",
    meetingInputLabel: "Meeting URL or Code",
    meetingInputPlaceholder: "Paste meeting URL (Google Meet, Zoom, or Teams)...",
    botName: "Bot Name",
    botNamePlaceholder: "Vexa",
    wakeWordLabel: "Kabosu wake word",
    wakeWordEnabledHelp: "Kabosu can react when called during the meeting.",
    wakeWordDisabledHelp: "Kabosu joins for recording and transcription only.",
    realtimeTranscription: "Real-time Transcription",
    recordOnly: "Bot will record audio only. You can transcribe later from the meeting page.",
    language: "Transcription Language",
    autoDetect: "Auto-detect: the service will detect the language automatically.",
    authenticated: "Authenticated",
    authenticatedHelp: "Joins the meeting signed in with your Google account. Coming soon.",
    soon: "Soon",
    passcodeLabelTeams: "Passcode (required for Teams)",
    passcodeLabelZoom: "Passcode (optional for Zoom)",
    passcodePlaceholder: "Enter meeting passcode",
    connecting: "Connecting...",
    startTranscription: "Start Transcription",
    startRecording: "Start Recording",
  },
};

const JA_DASHBOARD_COPY: typeof EN_DASHBOARD_COPY = {
  nav: {
    meetings: "会議",
    tracker: "トラッカー",
    dictionary: "文字起こし辞書",
    joinMeeting: "会議に参加",
    webhooks: "Webhook設定",
    mcpSetup: "MCP設定",
    profile: "プロフィール",
    admin: "管理",
    users: "ユーザー",
    bots: "ボット",
    settings: "設定",
    unlockAdmin: "管理を解除",
    apiDocs: "APIドキュメント",
    reportBug: "不具合を報告",
    accountBilling: "アカウントと請求",
    menu: "メニュー",
  },
  header: {
    toggleMenu: "メニューを開く",
    docsSr: "ドキュメント",
    docsTooltip: "APIドキュメントを開く",
    profileApiKey: "プロフィールとAPIキー",
    account: "アカウント",
    logout: "ログアウト",
  },
  billing: {
    trialPrefix: "トライアル",
    day: "日",
    days: "日",
    left: "残り",
    planExpired: "プラン期限切れ",
    subscribe: "契約する",
    activePlanSuffix: "プラン",
  },
  login: {
    heroTitle: "会議URLを入れて、ボットを参加させる",
    meetingPlaceholder: "会議URLを貼り付け...",
    invalidMeetingUrl: "有効な会議URLを入力してね",
    unsupportedPlatformToast: "現在はGoogle MeetとMicrosoft Teamsに対応しています",
    unsupportedPlatformHint: "現在はGoogle MeetとMicrosoft Teamsに対応しています",
    createMeet: "Meetを作成",
    signIn: "アカウントがある場合はログイン",
    footer: "オープンソース · 開発者向け · APIファースト",
    serverConfigErrorTitle: "サーバー設定エラー",
    serverConfigErrorDescription: "サーバー設定が不足しています。管理者に確認してください。",
    connectionWarningTitle: "接続警告",
    connectionWarningDescription: "一部のサービスが利用できない可能性があります。",
    signInTitle: "ログインして続ける",
    signInDescription: "利用するログイン方法を選択してください",
    continueGoogle: "Googleで続ける",
    continueMicrosoft: "Microsoftで続ける",
    or: "または",
    checkingServer: "サーバー確認中...",
    signingIn: "ログイン中...",
    sendingLink: "リンク送信中...",
    serverUnavailable: "サーバー利用不可",
    continueEmail: "メールで続ける",
    back: "戻る",
    checkEmailTitle: "メールを確認してください",
    checkEmailDescription: "マジックリンクを送信しました:",
    clickEmailLink: "メール内のリンクをクリックするとログインできます。",
    linkExpires: "リンクの有効期限は15分です。",
    sending: "送信中...",
    resendMagicLink: "マジックリンクを再送",
    differentEmail: "別のメールを使う",
    accountCreated: "アカウントを作成しました。{brand}へようこそ。",
    welcomeBack: "おかえりなさい。",
    magicLinkSent: "マジックリンクを送信しました。メールを確認してください。",
    magicLinkSentAgain: "マジックリンクを再送しました。メールを確認してください。",
    failedSend: "マジックリンクの送信に失敗しました",
    failedResend: "マジックリンクの再送に失敗しました",
    enterEmail: "メールアドレスを入力してください",
    failedGoogle: "Googleログインに失敗しました",
    failedMicrosoft: "Microsoftログインに失敗しました",
  },
  meetings: {
    subscriptionRequiredTitle: "契約が必要です",
    subscriptionRequiredMessage: "新しいボット作成とAPI利用にはプラン契約が必要です。",
    viewPlans: "プランを見る",
    title: "会議",
    description: "会議の文字起こしを一覧・検索できます",
    joinMeeting: "会議に参加",
    joinShort: "参加",
    searchPlaceholder: "会議を検索...",
    allPlatforms: "すべてのサービス",
    allStatus: "すべての状態",
    statuses: {
      active: "実行中",
      completed: "完了",
      failed: "失敗",
      joining: "参加中",
    },
    subscribeTitle: "契約して続ける",
    subscribeMessage:
      "トライアルが終了しました。ボット作成と会議文字起こしの閲覧にはプラン契約が必要です。",
    table: {
      platform: "サービス",
      meeting: "会議",
      status: "状態",
      duration: "時間",
      participants: "参加者",
      time: "日時",
    },
    noMatches: "条件に一致する会議はありません",
    noMeetings: "まだ会議がありません",
    joinFirst: "最初の会議に参加",
    participantsMeetingTitle: "{names} の会議",
    statusDescriptions: {
      stopped: "ユーザー操作またはシステムにより録音を停止しました",
      meetingEnded: "会議が終了したため文字起こしが完了しました",
      kicked: "ボットが会議から退出しました",
      admissionRejected: "ボットの入室が許可されませんでした",
      completed: "文字起こしまで正常に完了しました",
      failed: "処理中にエラーが発生しました",
      needsHumanHelp: "ボットが停止しているため、人による確認が必要です",
      active: "現在ボットが会議に参加し、記録・文字起こし中です",
      joining: "ボットが会議への接続を試みています",
      awaitingAdmission: "ロビーで入室許可を待っています",
      requested: "ボットの起動をリクエストしました",
      stopping: "録音を停止する処理を実行しています",
      unknown: "現在の状態を確認できません",
    },
  },
  joinModal: {
    title: "会議に参加",
    description: "Google Meet、Zoom、TeamsのURLを貼ると自動で文字起こしを開始します",
    modeMeeting: "会議",
    modeBrowser: "ブラウザ",
    modeMeetingDescription: "Google Meet、Zoom、TeamsのURLにボットが参加して文字起こしします。",
    modeBrowserDescription: "VNCやCDPから操作できる常駐リモートブラウザを起動します。",
    browserDescription: "VNC、CDP、SSH付きのリモートブラウザです。Gitワークスペースはプロフィールで設定します。",
    starting: "開始中...",
    startBrowserSession: "ブラウザセッションを開始",
    invalidTitle: "会議URLを確認してください",
    invalidDescription: "Google Meet、Zoom、TeamsのURLまたは会議コードを入力してください",
    platformRequiredTitle: "サービス選択が必要です",
    platformRequiredDescription:
      "このURLは会議リンクとして認識されましたが、サービスを自動判定できません。Google Meet、Zoom、Teamsから選択してください。",
    passcodeRequiredTitle: "パスコードが必要です",
    passcodeRequiredDescription: "Microsoft Teamsの会議にはパスコードが必要です",
    botJoining: "ボットが会議に参加中です",
    botJoiningDescription: "文字起こしボットが接続しています...",
    subscriptionRequiredTitle: "契約が必要です",
    subscriptionRequiredDescription: "ボットを作成するにはプラン契約が必要です。",
    zoomAuthTitle: "Zoom認証が必要です",
    zoomAuthDescription:
      "Zoomへ移動します。アプリ利用権限のあるZoomアカウントでログインしてください。",
    zoomAuthStartFailed: "Zoom認証の開始に失敗しました",
    platformNeeded:
      "会議リンクとして認識しましたが、サービスを自動判定できませんでした。サービスを選ぶと、ボットがそのURLへ直接移動します。",
    platformRadioLabel: "会議サービスを選択",
    meetingInputLabel: "会議URLまたはコード",
    meetingInputPlaceholder: "会議URLを貼り付け（Google Meet、Zoom、Teams）...",
    botName: "ボット名",
    botNamePlaceholder: "カボス",
    wakeWordLabel: "カボスのウェイクワード起動",
    wakeWordEnabledHelp: "会議中にカボスを呼びかけで起動できます。",
    wakeWordDisabledHelp: "録音と文字起こしだけ行い、呼びかけでは起動しません。",
    realtimeTranscription: "リアルタイム文字起こし",
    recordOnly: "音声のみ録音します。文字起こしは会議ページから後で実行できます。",
    language: "文字起こし言語",
    autoDetect: "自動判定: サービスが言語を自動判定します。",
    authenticated: "認証済み参加",
    authenticatedHelp: "Googleアカウントで認証した状態で会議に参加する機能です。近日提供予定。",
    soon: "近日",
    passcodeLabelTeams: "パスコード（Teamsは必須）",
    passcodeLabelZoom: "パスコード（Zoomは任意）",
    passcodePlaceholder: "会議パスコードを入力",
    connecting: "接続中...",
    startTranscription: "文字起こしを開始",
    startRecording: "録音を開始",
  },
};

export type DashboardCopy = typeof EN_DASHBOARD_COPY;

export function getDashboardCopy(locale?: DashboardLocale | string | null): DashboardCopy {
  return locale === "ja" ? JA_DASHBOARD_COPY : EN_DASHBOARD_COPY;
}
